---
- name: "PRELIM | Set variable for postgresql-server service name"
  ansible.builtin.set_fact:
      pg15cis_postgresql_service_default: "{{ (ansible_os_family == 'Debian') | ternary('postgresql', 'postgresql-15') }}"

- name: "PRELIM | Get postgres config file path"
  ansible.builtin.shell: psql -U postgres -c 'SHOW config_file' | tail -n+3 | head -n 1 | cut -c2-
  changed_when: false
  failed_when: false
  #become_user: "{{ pg15cis_pgs_usr }}"
  become_user: postgres
  register: pg15cis_config_file_get

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: pg15cis_config_file_get
    verbosity: 1

