---
# handlers file for kn-cis-pg-15
- name: restart postgresql
  ansible.builtin.service:
      name: "{{ pg15cis_postgresql_service }}"
      state: restarted

- name: pg_reload_conf
  ansible.builtin.shell: psql -t -c "select pg_reload_conf()"
  become_user: "{{ pg15cis_postgres_user }}"

- name: reboot system
  ansible.builtin.shell: sleep 3; reboot
  async: 15
  poll: 0

