- name: "GET | 3.1.25 Get current 'log_statement' setting"
  ansible.builtin.shell: psql -t -c "show log_statement" | head -1 | xargs
  changed_when: false
  failed_when: pg15cis_postgres_log_statement_get.stderr
  become_user: "{{ pg15cis_postgres_user }}"
  register: pg15cis_postgres_log_statement_get
  when:
      - pg15cis_rule_3_1_25
  tags:
      - level_1
      - level_2
      - get
      - fix
      - rule_3_1_25


- name: "FIX | 3.1.25 Ensure 'log_statement' is set correctly"
  ansible.builtin.shell: psql -t -c "alter system set log_statement = '{{pg15cis_log_statement}}'"
  changed_when: pg15cis_postgres_log_statement_get.stdout != pg15cis_log_statement
  register: result
  failed_when: result.stderr
  become_user: "{{ pg15cis_postgres_user }}"
  notify: pg_reload_conf
  when:
      - pg15cis_rule_3_1_25
  tags:
      - level_1
      - level_2
      - fix
      - rule_3_1_25
