- name: "GET | 3.1.26 Get current 'log_timezone' setting"
  ansible.builtin.shell: psql -t -c "show log_timezone" | head -1 | xargs
  changed_when: false
  failed_when: pg15cis_postgres_log_timezone_get.stderr
  become_user: "{{ pg15cis_postgres_user }}"
  register: pg15cis_postgres_log_timezone_get
  when:
      - pg15cis_rule_3_1_26
  tags:
      - level_1
      - level_2
      - get
      - fix
      - rule_3_1_26


- name: "FIX | 3.1.26 Ensure 'log_timezone' is set correctly"
  ansible.builtin.shell: psql -t -c "alter system set log_timezone = '{{pg15cis_log_timezone}}'"
  changed_when: pg15cis_postgres_log_timezone_get.stdout != pg15cis_log_timezone
  register: result
  failed_when: result.stderr
  become_user: "{{ pg15cis_postgres_user }}"
  notify: pg_reload_conf
  when:
      - pg15cis_rule_3_1_26
  tags:
      - level_1
      - level_2
      - fix
      - rule_3_1_26
