- name: "GET | 3.1.21 Get current 'log_disconnections' setting"
  ansible.builtin.shell: psql -t -c "show log_disconnections" | head -1 | xargs
  changed_when: false
  failed_when: pg15cis_postgres_log_disconnections_get.stderr
  become_user: "{{ pg15cis_postgres_user }}"
  register: pg15cis_postgres_log_disconnections_get
  when:
      - pg15cis_rule_3_1_21
  tags:
      - level_1
      - level_2
      - get
      - fix
      - rule_3_1_21


- name: "FIX | 3.1.21 Ensure 'log_disconnections' is enabled"
  ansible.builtin.shell: psql -t -c "alter system set log_disconnections = 'on'"
  changed_when: pg15cis_postgres_log_disconnections_get.stdout != 'on'
  register: result
  failed_when: result.stderr
  become_user: "{{ pg15cis_postgres_user }}"
  notify: pg_reload_conf
  when:
      - pg15cis_rule_3_1_21
  tags:
      - level_1
      - level_2
      - fix
      - rule_3_1_21
