- name: "GET | 3.1.7 Get current log file permissions"
  ansible.builtin.shell: psql -t -c "show log_truncate_on_rotation" | head -1 | xargs
  changed_when: false
  failed_when: pg15cis_postgres_log_truncate_on_rotation_get.stderr
  become_user: "{{ pg15cis_postgres_user }}"
  register: pg15cis_postgres_log_truncate_on_rotation_get
  when:
      - pg15cis_rule_3_1_7
  tags:
      - level_1
      - level_2
      - get
      - fix
      - rule_3_1_7


- name: "FIX | 3.1.7 Ensure the log file permissions are set correctly"
  ansible.builtin.shell: psql -t -c "alter system set log_truncate_on_rotation = '{{pg15cis_log_truncate_on_rotation}}'"
  changed_when: pg15cis_postgres_log_truncate_on_rotation_get.stdout != pg15cis_log_truncate_on_rotation
  register: result
  failed_when: result.stderr
  become_user: "{{ pg15cis_postgres_user }}"
  notify: pg_reload_conf
  when:
      - pg15cis_rule_3_1_7
  tags:
      - level_1
      - level_2
      - fix
      - rule_3_1_7
