- name: "3.1.3 Get Logging Collector Status"
  ansible.builtin.shell: psql -t -c "show logging_collector" | head -1 | xargs
  changed_when: false
  failed_when: pg15cis_postgres_logging_collector_get.rc != 0
  become_user: "{{ pg15cis_postgres_user }}"
  register: pg15cis_postgres_logging_collector_get
  when:
      - pg15cis_rule_3_1_3
  tags:
      - level_1
      - level_2
      - get
      - fix
      - rule_3_1_3


- name: "3.1.3 Ensure the logging collector is enabled"
  ansible.builtin.shell: psql -t -c "alter system set logging_collector = 'on'"
  changed_when: pg15cis_postgres_logging_collector_get.stdout != 'on'
  register: result
  failed_when: result.rc != 0
  become_user: "{{ pg15cis_postgres_user }}"
  notify: restart postgresql
  when:
      - pg15cis_rule_3_1_3
  tags:
      - level_1
      - level_2
      - fix
      - rule_3_1_3
