- name: "GET | 3.1.23 Get current 'log_hostname' setting"
  ansible.builtin.shell: psql -t -c "show log_hostname" | head -1 | xargs
  changed_when: false
  failed_when: pg15cis_postgres_log_hostname_get.stderr
  become_user: "{{ pg15cis_postgres_user }}"
  register: pg15cis_postgres_log_hostname_get
  when:
      - pg15cis_rule_3_1_23
  tags:
      - level_1
      - level_2
      - get
      - fix
      - rule_3_1_23


- name: "FIX | 3.1.23 Ensure 'log_hostname' is set correctly"
  ansible.builtin.shell: psql -t -c "alter system set log_hostname = '{{pg15cis_log_hostname}}'"
  changed_when: pg15cis_postgres_log_hostname_get.stdout != pg15cis_log_hostname
  register: result
  failed_when: result.stderr
  become_user: "{{ pg15cis_postgres_user }}"
  notify: pg_reload_conf
  when:
      - pg15cis_rule_3_1_23
  tags:
      - level_1
      - level_2
      - fix
      - rule_3_1_23
