- name: "GET | 3.1.22 Get current 'log_error_verbosity' setting"
  ansible.builtin.shell: psql -t -c "show log_error_verbosity" | head -1 | xargs
  changed_when: false
  failed_when: pg15cis_postgres_log_error_verbosity_get.stderr
  become_user: "{{ pg15cis_postgres_user }}"
  register: pg15cis_postgres_log_error_verbosity_get
  when:
      - pg15cis_rule_3_1_22
  tags:
      - level_1
      - level_2
      - get
      - fix
      - rule_3_1_22


- name: "FIX | 3.1.22 Ensure 'log_error_verbosity' is set correctly"
  ansible.builtin.shell: psql -t -c "alter system set log_error_verbosity = '{{pg15cis_log_error_verbosity}}'"
  changed_when: pg15cis_postgres_log_error_verbosity_get.stdout != pg15cis_log_error_verbosity
  register: result
  failed_when: result.stderr
  become_user: "{{ pg15cis_postgres_user }}"
  notify: pg_reload_conf
  when:
      - pg15cis_rule_3_1_22
  tags:
      - level_1
      - level_2
      - fix
      - rule_3_1_22
