- name: "GET | 3.1.20 Get current 'log_connections' setting"
  ansible.builtin.shell: psql -t -c "show log_connections" | head -1 | xargs
  changed_when: false
  failed_when: pg15cis_postgres_log_connections_get.stderr
  become_user: "{{ pg15cis_postgres_user }}"
  register: pg15cis_postgres_log_connections_get
  when:
      - pg15cis_rule_3_1_20
  tags:
      - level_1
      - level_2
      - get
      - fix
      - rule_3_1_20


- name: "FIX | 3.1.20 Ensure 'log_connections' is enabled"
  ansible.builtin.shell: psql -t -c "alter system set log_connections = 'on'"
  changed_when: pg15cis_postgres_log_connections_get.stdout != 'on'
  register: result
  failed_when: result.stderr
  become_user: "{{ pg15cis_postgres_user }}"
  notify: pg_reload_conf
  when:
      - pg15cis_rule_3_1_20
  tags:
      - level_1
      - level_2
      - fix
      - rule_3_1_20
